locallibrary/catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('borrowed/', views.LoanedBooksAllListView.as_view(), name='all-borrowed'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
]

locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from locallibrary import settings
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/')),
    path('accounts/', include('django.contrib.auth.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

locallibrary/catalog/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _ # Update i18n standard
from datetime import date
from django.contrib.auth.models import User

import uuid

class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(max_length=200, help_text=_('Enter a book genre (e.g. Science Fiction)'))

    def __str__(self):
        """String for representing the Model object."""
        return self.name

class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)
    
    # CAC GIA TRI KHAC CUA ON_DELETE:
    # - CASCADE: Xoa tat ca cac ban ghi lien quan khi ban ghi doi tuong duoc tham chieu bi xoa.
    # - PROTECT: Khong cho xoa ban ghi neu co ban ghi lien quan toi no. Neu co gang xoa, Django se nem ra mot loi ProtectedError.
    # - SET_NULL: Dat truong quan he tren doi tuong lien quan la NULL khi ban ghi doi tuong duoc tham chieu bi xoa. 
    # - SET_DEFAULT: Dat truong quan he tren doi tuong lien quan la gia tri mac dinh khi ban ghi doi tuong duoc tham chieu bi xoa.
    # - SET(): Dat truong quan he tren doi tuong lien quan la gia tri chi dinh khi ban ghi doi tuong duoc tham chieu bi xoa.
    # - DO_NOTHING: Khong lam gi ca. Neu co gang xoa ban ghi, co the bi pha huy cac rang buoc khoa ngoai cua CSDL.
    # - RESTRICT: Giong nhu PROTECT. Nhung cho phep xoa doi tuong neu viec do khong vi pham rang buoc khoa ngoai. trong mot Transaction.

    author = models.ForeignKey('Author', on_delete=models.RESTRICT, null=True)

    summary = models.TextField(max_length=1000, help_text=_("Enter a brief description of the book"))
    isbn = models.CharField(_('ISBN'), max_length=13,
                            unique=True,
                            help_text=_('13 Character <a href="https://www.isbn-international.org/content/what-isbn'
                                        '">ISBN number</a>'))


    genre = models.ManyToManyField(Genre, help_text=_("Select a genre for this book"))

    # Dinh nghia cac mot object cua model duoc chuyen thanh chuoi, o day phuong thuc tra ve gia tri dang chuoi cua truong title
    def __str__(self):
        """String for representing the Model object."""
        return self.title
    # Dinh nghia duong dan tuyet doi den mot chi tiet ban ghi cho cuon sach nay, o day method su dung reverse() de tao URL dua tren 
    # pattern 'book-detail' va tham so la id cua ban ghi
    def get_absolute_url(self):
        """Returns the URL to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])
    
    # Dinh nghia phuong thuc de hien thi cac the loai cua cuon sach nay, phuong thuc nay duoc yeu cau de hien thi the loai trong Admin
    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'


class BookInstance(models.Model):

    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text=_("Unique ID for this particular book across whole library"))
    book = models.ForeignKey('Book', on_delete=models.RESTRICT)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    creation_date = models.DateField(default=date.today) # Ngay tao ban copy
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    class BookStatus(models.TextChoices):
        MAINTENANCE = ('m', _('Maintenance'))
        ON_LOAN = ('o', _('On loan'))
        AVAILABLE = ('a', _('Available'))
        RESERVED = ('r', _('Reserved'))

    status = models.CharField(
        max_length=1,
        choices=BookStatus.choices,
        default=BookStatus.AVAILABLE,
    )
    # Chi dinh cac ban ghi se duoc sap xep theo truong 'due_back'
    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", _("Set book as returned")),)

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'
    
    @property
    def is_overdue(self):
        return self.due_back and date.today() > self.due_back

    
class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    # Chi dinh cac ban ghi se duoc sap xep theo truong 'last_name' va 'first_name'
    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the URL to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'

    

locallibrary/catalog/forms.py
import datetime

from django import forms
from django.forms import ModelForm
from catalog.models import BookInstance

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

class DateValidationMixin:
    def validate_date(self, date):
        if date < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))
        if date > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))
        
class RenewBookForm(forms.Form, DateValidationMixin):
    renewal_date = forms.DateField(help_text=_("Enter a date between now and 4 weeks (default 3)."))

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']
        self.validate_date(data)
        return data

class RenewBookModelForm(ModelForm, DateValidationMixin):
    def clean_due_back(self):
        data = self.cleaned_data['due_back']
        self.validate_date(data)
        return data

    class Meta:
        model = BookInstance
        fields = ['due_back']
        labels = {'due_back': _('Renewal date')}
        help_texts = {'due_back': _('Enter a date between now and 4 weeks (default 3).')}

locallibrary/catalog/views.py
import datetime

from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Book, Author, BookInstance, Genre
from django.views import generic
from .constants import ITEMS_PER_PAGE, BOOKINSTANCE_LIST_BORROWED_USER_PER_PAGE
from django.contrib.auth.mixins import LoginRequiredMixin
from catalog.forms import RenewBookForm
from django.contrib.auth.mixins import PermissionRequiredMixin


from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Author

@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_book_librarian(request, pk):
    """View function for renewing a specific BookInstance by librarian."""
    book_instance = get_object_or_404(BookInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':
        form = RenewBookForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('all-borrowed'))

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'catalog/book_renew_librarian.html', context)

def book_detail_view(request, pk):
    # Lay thong tin cuon sach tu csdl dua vao id, neu khong ton tai thi tra ve 404
    book = get_object_or_404(Book, pk=pk)
    # Sap xep genre theo alphabet
    genres = book.genre.all().order_by('name')
    # Sap xep cac ban copy theo ngay tao
    book_instances = BookInstance.objects.all().order_by('creation_date')
    return render(request, 'catalog/book_detail.html', {'book': book, 'genres': genres, 'book_instances': book_instances})

def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_books = Book.objects.count()
    num_instances = BookInstance.objects.count()

    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact=BookInstance.BookStatus.AVAILABLE).count()

    # The 'all()' is implied by default.
    num_authors = Author.objects.count()

    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_visits': num_visits,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)

class BookListView(generic.ListView):
    model = Book
    paginate_by = ITEMS_PER_PAGE

    # select_related su dung cho quan he one-to-one hoac many-to-one
    # prefetch_related su dung cho quan he many-to-many hoac reverse many-to-one (truong hop nguoc lai cua ForeignKey)
    def get_queryset(self):
        # Su dung select_related de lay thong tin cua author cung luc khi query book
        return Book.objects.select_related('author').all()
    
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(BookListView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['some_data'] = 'This is just some data'
        return context

class BookDetailView(generic.DetailView):
    model = Book

class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = BOOKINSTANCE_LIST_BORROWED_USER_PER_PAGE

    def get_queryset(self):
        return (
            BookInstance.objects.filter(borrower=self.request.user)
            .filter(status__exact='o')
            .select_related('book')
            .order_by('due_back')
        )

class LoanedBooksAllListView(PermissionRequiredMixin, generic.ListView):
    model = BookInstance
    permission_required = 'catalog.can_mark_returned'
    template_name = 'all-borrowed.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back').select_related('borrower')
    
class AuthorListView(generic.ListView):
    """Generic class-based list view for a list of authors."""
    model = Author
    paginate_by = ITEMS_PER_PAGE

class AuthorDetailView(generic.DetailView):
    """Generic class-based detail view for an author."""
    model = Author

class AuthorCreate(CreateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    initial = {'date_of_death': '11/11/2023'}

class AuthorUpdate(UpdateView):
    model = Author
    # Not recommended (potential security issue if more fields added)
    fields = '__all__'

class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('authors')
    

locallibrary/catalog/templates/all-borrowed.html
{% extends "base_generic.html" %}
{% load i18n %}
{% block content %}
    <h1>{% trans "All Borrowed Books" %}</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> ({{ bookinst.due_back }}) {% if user.is_staff %}- {{ bookinst.borrower }}{% endif %}
      </li>
      {% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew-book-librarian' bookinst.id %}">{% trans "Renew" %}</a>{% endif %}
      {% endfor %}
    </ul>

    {% else %}
      <p>{% trans "There are no books borrowed." %}</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  {% load i18n %}
  {% block title %}
  <title>Local Library</title>
  {% endblock %}
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
  <!-- Add additional CSS in static file -->
  <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
</head>

<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
        {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">{% trans "Home" %}</a></li>
          <li><a href="{% url 'books' %}">{% trans "All books" %}</a></li>
          <li><a href="{% url 'authors' %}">{% trans "All authors" %}</a></li>
        </ul>
        {% if user.is_authenticated %}
          <li>{% trans "User:" %} {{ user.get_username }}</li>
          <li><a href="{% url 'my-borrowed' %}">{% trans "My Borrowed" %}</a></li>
          <li>
            <form id="logout-form" method="post" action="{% url 'logout' %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-link">{% trans "Logout" %}</button>
            </form>
          </li>
        {% else %}
          <li><a href="{% url 'login' %}?next={{ request.path }}">{% trans "Login" %}</a></li>
        {% endif %}

        {% if user.is_staff %}
          <hr>
          <ul class="sidebar-nav">
          <li>{% trans "Staff" %}</li>
          <li><a href="{% url 'all-borrowed' %}">{% trans "All borrowed" %}</a></li>
          {% if perms.catalog.add_author %}
            <li><a href="{% url 'author-create' %}">{% trans "Create author" %}</a></li>
          {% endif %}
          </ul>
        {% endif %}
        {% endblock %}
      </div>
      <div class="col-sm-10">
        {% block content %}{% endblock %}
        {% block pagination %}
        {% if is_paginated %}
        <div class="pagination">
          <span class="page-links">
            {% if page_obj.has_previous %}
            <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">{% trans "previous" %}</a>
            {% endif %}
            <span class="page-current">
              {% blocktrans %}Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.{% endblocktrans %}
            </span>
            {% if page_obj.has_next %}
            <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">{% trans "next" %}</a>
            {% endif %}
          </span>
        </div>
        {% endif %}
        {% endblock %}
      </div>
    </div>
  </div>
  <script src="{% static 'js/jquery-3.5.1.slim.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>

</html>

locallibrary/catalog/templates/index.html
{# this template extends the base_generic.html template #}
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
<h1>{% trans "Local Library Home" %}</h1>
<p>
  {% trans "Welcome to LocalLibrary, a website developed by" %}
  <em>{% trans "Mozilla Developer Network" %}</em>!
</p>
<h2>{% trans "Dynamic content" %}</h2>
<p>{% trans "The library has the following record counts:" %}</p>
<ul>
  <li><strong>{% trans "Books:" %}</strong> {{ num_books }}</li>
  <li><strong>{% trans "Copies:" %}</strong> {{ num_instances }}</li>
  <li><strong>{% trans "Copies available:" %}</strong> {{ num_instances_available }}</li>
  <li><strong>{% trans "Authors:" %}</strong> {{ num_authors }}</li>
</ul>
<p>
  {% trans "You have visited this page " %} {{ num_visits }} time{{ num_visits|pluralize }}.
</p>
{% endblock %}